name: nteractive
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - requests
  - seaborn
  - traitlets
  - vega_datasets
  - pip:
    - dx
    - vdom
