name: nteractive
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - matplotlib
  - nteract_on_jupyter
  - numpy
  - pandas
  - pip
  - plotly
  - requests
  - seaborn
  - traitlets
  - vdom
  - vega_datasets
